# Settings
baseURL = "https://amherstlawreview.github.io/"
languageCode = "en-US" # or en-US
title = "amherstlawreview.github.io"
description = "Amherst Law Review"
theme = ["hugo-redirect", "basic"]
canonifyURLs = true
copyright = "Amherst College Law Review"
enableRobotsTXT = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
    unsafe = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"
